spring:
  application:
    name: ms-product-management
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: true
  data:
    rest:
      detection-strategy: annotated

auto-spare:
  scm:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/autosparescm
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8021
  servlet:
    context-path: /productmanagementservices

springdoc:
  api-docs:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8041/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000